apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: web-ip
spec:
  replicas: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: natakravchenko/ci-demo
          ports:
            - containerPort: 8080