name: My first workflow
on: [workflow_dispatch]
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
     - name: Welcome message
       run: echo 'Hello from ${{ github.workflow }}'
     - name: Java program execution
       run: |
          echo 'public class Hello { public static void main(String args[]) { System.out.println("Hello"); } }' >> Hello.java
          javac Hello.java
          ls
          java Hello
          echo 'By-bye'
     - uses: actions/upload-artifact@v3
       with:
          name: my-artifact
          path: ${{ github.workspace }}/Hello.java
  job2: 
    needs: job1
    runs-on: ubuntu-latest
    steps:
     - name: Welcome message
       run: echo 'Hello from ${{ github.workflow }}'
     - name: Download artifact from prev job(job1)
       uses: actions/download-artifact@v3
       with:
         name: my-artifact     
     - name: ls
       run: ls -a
    
      
    
